name: Print Pushed File Name
on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  print-file-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1

      - name: Print pushed file name
        run: |
          echo "Pushed file:"
          for chenged_file in ${{ steps.files.outputs.all}}; do
            echo "Changed files: ${chenged_file}"
