name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Check if file is a text file
      run: |
        if [[ $(file -b "${GITHUB_WORKSPACE}/${{ github.event.head_commit.modified[0] }}") == "ASCII text"* ]]; then
          echo "The file is a text file."
        else
          echo "The file is not a text file."
          exit 1
        fi
