name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: List all changed files
      run: |
        for file in ${{ steps.changed-directories.outputs.all_changed_and_modified_files }}; do
          echo $file
        done
