name: Print Pushed File Name
on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  print-file-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print pushed file name
        run: |
          echo "Pushed file:"
          echo "${{ github.event.head_commit.modified[0] }}"
