name: Print Pushed File Name
on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  print-file-name:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: files

      - name: Print pushed file name
        run: |
          echo "Pushed files:"
          for changed_file in ${{ steps.files.outputs.all}}; do
            echo "Changed file: ${changed_file}"
            if file -b "${changed_file}" | grep -q "text"; then
              echo "The file '${changed_file}' is a text file."
            else
              echo "The file '${changed_file}' is not a text file."
              # Handle the case when the file is not a text file
            fi
          done
