name: Print All Files
on:
  push:
    branches:
      - main # Replace with your desired branch

jobs:
  print-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print all files
        run: |
          echo "All files in the repository:"
          find . -type f
