name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Check if files are text files
      run: |
        for file in ${{ github.event.commits[0].added }}; do
          echo "File: $file"
          if [[ $(file -b "${GITHUB_WORKSPACE}/$file") == "ASCII text"* ]]; then
            echo "The file is a text file."
          else
            echo "The file is not a text file."
            exit 1
          fi
        done
